const images = [
  {
    category: "Astrophotography",
    name: "Maroon Bells",
    code: "Maroon-Bells-Night",
    imageUrl: "Maroon-Bells-Night",
    location: "Aspen, Colorado",
    date: "2/1/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 0,
    latitude: 39.0981336,
    longitude: -106.9447112,
  },
  {
    category: "Underwater",
    name: "Sunset Silkies",
    code: "Sunset-Silkies",
    imageUrl: "Sunset-Silkies",
    location: "Jardines de la Reina, Cuba",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Sharks", "Cuba"],
    order: 0,
    latitude: 20.84,
    longitude: -78.93,
  },
  {
    category: "Aerial",
    name: "Seven Mile Bridge",
    code: "Seven-Mile-Bridge",
    imageUrl: "Florida-Keys",
    location: "Florida Keys",
    date: "1/24/2016",
    camera: "DJI Phantom 3 Pro",
    tags: ["Ocean"],
    order: 0,
    latitude: 24.6880479,
    longitude: -81.223883,
  },

  {
    category: "Underwater",
    name: "American Crocodile",
    code: "American-Crocodile",
    imageUrl: "American-Crocodile",
    location: "Jardines de la Reina, Cuba",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Cuba", "Crocodile", "Reptiles"],
    order: 10,
    latitude: 20.769608,
    longitude: -78.816386,
  },

  {
    category: "Underwater",
    name: "Crocodile Sunset",
    code: "Crocodile-Sunset",
    imageUrl: "Optimized/Crocodile-Sunset",
    location: "Jardines de la Reina, Cuba",
    date: "2/10/2020",
    camera: "Canon EOS 5D Mk III",
    tags: ["Cuba", "Crocodile", "Reptiles"],
    order: 10,
    latitude: 20.8408089,
    longitude: -79.0181599,
  },
  {
    category: "Underwater",
    name: "Golden Rays",
    code: "Golden-Rays",
    imageUrl: "Golden-Rays",
    location: "Galápagos, Ecuador",
    date: "9/25/2016",
    camera: "Canon EOS 5D Mk III",
    tags: ["Galápagos"],
    order: 20,
    latitude: -0.948353,
    longitude: -90.9809562,
  },

  {
    category: "Underwater",
    name: "Humpback Portrait",
    code: "Humpback-Portrait",
    imageUrl: "Humpback-Portrait",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Whales", "French Polynesia"],
    order: 30,
    latitude: -17.5319519,
    longitude: -149.923031,
  },

  {
    category: "Underwater",
    name: "Humpbacks",
    code: "Humpbacks",
    imageUrl: "Optimized/Humpbacks",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Whales", "French Polynesia"],
    order: 30,
    latitude: -17.4234619,
    longitude: -149.938322,
  },
  {
    category: "Underwater",
    name: "Humpbacks Surfacing",
    code: "Humpbacks-Surfacing",
    imageUrl: "humpbacks-surfacing",
    location: "Moorea, French Polynesia",
    date: "5/17/2016",
    camera: "Canon EOS 5D Mk III",
    tags: ["Whales", "French Polynesia"],
    order: 45,
    latitude: -17.460267,
    longitude: -149.8706031,
  },
  {
    category: "Underwater",
    name: "Kelp Forest",
    code: "Kelp-Forest",
    imageUrl: "kelp-forest",
    location: "Santa Barbara Island, California",
    date: "7/26/2015",
    camera: "Canon EOS 5D Mk III",
    tags: ["California", "Kelp Forest"],
    order: 50,
    latitude: 33.4769828,
    longitude: -119.0472799,
  },
  {
    category: "Underwater",
    name: "American Crocodile",
    code: "American-Crocodile-Swimming",
    imageUrl: "American-Crocodile-Swimming",
    location: "Jardines de la Reina, Cuba",
    date: "7/6/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Crocodiles", "Cuba"],
    order: 100,
    latitude: 20.8416771,
    longitude: -78.9375894,
  },
  {
    category: "Landscape",
    name: "Aspen",
    code: "Aspen-Colorado",
    imageUrl: "Aspen-Colorado",
    location: "Aspen, Colorado",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
    latitude: 39.0981336,
    longitude: -106.9447112,
  },
  {
    category: "Astrophotography",
    name: "Aurora Australis",
    code: "Aurora-Wanaka-New-Zealand",
    imageUrl: "Aurora-Wanaka-New-Zealand",
    location: "Wanaka, New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Wanaka", "New Zealand"],
    order: 100,
    latitude: -44.7163518,
    longitude: 168.9702668,
  },

  {
    category: "Landscape",
    name: "Bartolome Island",
    code: "Bartolome-Galapagos",
    imageUrl: "Bartolome-Galapagos",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Galápagos"],
    order: 100,
    latitude: -0.285123,
    longitude: -90.5590905,
  },
  {
    category: "Underwater",
    name: "Galapagos Reef",
    code: "Galapagos-Reef",
    imageUrl: "Optimized/Galapagos-Reef",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Galápagos"],
    order: 100,
    latitude: -0.0155736,
    longitude: -91.189021,
  },

  {
    category: "Astrophotography",
    name: "Boulder Flatirons",
    code: "Boulder-Colorado",
    imageUrl: "Boulder-Colorado",
    location: "Boulder, Colorado",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
    latitude: 39.999479,
    longitude: -105.281133,
  },
  {
    category: "Underwater",
    name: "Carwash Cenote",
    code: "Carwash-Cenote",
    imageUrl: "Carwash-Cenote",
    location: "Mexico",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Mexico", "Cenotes"],
    order: 100,
    latitude: 20.2741613,
    longitude: -87.4883593,
  },

  {
    category: "Aerial",
    name: "Colorado",
    code: "Colorado-Snow-Aerial",
    imageUrl: "Colorado-Snow-Aerial",
    location: "Aspen, Colorado",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Colorado"],
    order: 100,
    latitude: 39.0981336,
    longitude: -106.9447112,
  },
  {
    category: "Underwater",
    name: "Cuba Reef",
    code: "Cuba-Reef",
    imageUrl: "Cuba-Reef",
    location: "Jardines de la Reina, Cuba",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Cuba"],
    order: 100,
    latitude: 20.8416771,
    longitude: -78.9375894,
  },
  {
    category: "Underwater",
    name: "Cuernos",
    code: "Cuernos-Splitshot",
    imageUrl: "Cuernos-Splishot",
    location: "Torres del Paine, Patagonia, Chile",
    date: "7/10/2016",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Torres del Paine"],
    order: 100,
    latitude: -51.0368291,
    longitude: -73.0170619,
  },

  {
    category: "Aerial",
    name: "Darwin\u0027s Arch",
    code: "Darwins-Arch-Galapagos",
    imageUrl: "Darwins-Arch-Galapagos",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Galápagos"],
    order: 100,
    latitude: 1.6718717,
    longitude: -91.9907743,
  },
  {
    category: "Underwater",
    name: "Davidsgja",
    code: "Davidsgja",
    imageUrl: "Davidsgja",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Iceland"],
    order: 100,
    latitude: 64.2313204,
    longitude: -21.0814974,
  },
  {
    category: "Underwater",
    name: "Dream Gate Cenote",
    code: "Dreamgate",
    imageUrl: "Dreamgate",
    location: "Mexico",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Cenotes", "Mexico"],
    order: 100,
    latitude: 20.3052444,
    longitude: -87.3929751,
  },
  {
    category: "Aerial",
    name: "Dynjandi",
    code: "Dynjandi-Iceland",
    imageUrl: "Dynjandi-Iceland",
    location: "Iceland",
    date: "1/28/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Iceland", "Waterfalls"],
    order: 100,
    latitude: 65.7328135,
    longitude: -23.2020307,
  },
  {
    category: "Landscape",
    name: "Gjáin",
    code: "Gjáin-Iceland",
    imageUrl: "Gjáin-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Iceland"],
    order: 100,
    latitude: 64.1491952,
    longitude: -19.7402001,
  },

  {
    category: "Aerial",
    name: "Vatnajokull Glacier",
    code: "Glacier-Iceland",
    imageUrl: "Glacier-Iceland",
    location: "Iceland",
    date: "1/27/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Iceland"],
    order: 100,
    latitude: 64.0051645,
    longitude: -16.8602883,
  },
  {
    category: "Landscape",
    name: "Golden Aspens",
    code: "Golden-Aspens-Vail-Colorado",
    imageUrl: "Golden-Aspens-Vail-Colorado",
    location: "Vail, Colorado",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
    latitude: 39.0981336,
    longitude: -106.9447112,
  },
  {
    category: "Astrophotography",
    name: "Great Sand Dunes",
    code: "Great-Sand-Dunes-Colorado",
    imageUrl: "Great-Sand-Dunes-Colorado",
    location: "Colorado",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
    latitude: 37.7551467,
    longitude: -105.752133,
  },
  {
    category: "Underwater",
    name: "Green Sea Turtle",
    code: "Green-Sea-Turtle",
    imageUrl: "Green-Sea-Turtle",
    location: "Red Sea, Egypt",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Egypt", "Turtles"],
    order: 100,
    latitude: 22.78171,
    longitude: 37.583083,
  },
  {
    category: "Aerial",
    name: "Haiti Aerial",
    code: "Haiti-Aerial",
    imageUrl: "Haiti-Aerial",
    location: "Haiti",
    date: "1/31/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
    latitude: 18.8744941,
    longitude: -72.713696,
  },
  {
    category: "Underwater",
    name: "Humback Inversion",
    code: "Humback-Inversion",
    imageUrl: "Humpback-Inversion",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -17.5681909,
    longitude: -149.913051,
  },
  {
    category: "Underwater",
    name: "Humback Whales",
    code: "Humback-Whales",
    imageUrl: "Humpback-Whales",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -17.4518659,
    longitude: -149.785044,
  },
  {
    category: "Aerial",
    name: "Hverir",
    code: "Hverir-Iceland",
    imageUrl: "Hverir-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Iceland"],
    order: 100,
    latitude: 65.6409166,
    longitude: -16.811505,
  },
  {
    category: "Landscape",
    name: "Icelandic Farm",
    code: "Icelandic-Farm",
    imageUrl: "Icelandic-Farm",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Iceland"],
    order: 100,
    latitude: 64.2117142,
    longitude: -21.795013,
  },
  {
    category: "Landscape",
    name: "Kirkjufellsfoss",
    code: "Kirkjufellsfoss-Iceland",
    imageUrl: "Kirkjufell-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Iceland"],
    order: 100,
    latitude: 64.9261547,
    longitude: -23.3115577,
  },
  {
    category: "Aerial",
    name: "Kirkjufell Mountain, Iceland",
    code: "Kirkjufell-Iceland",
    imageUrl: "Kirkjufell-Aerial-Iceland",
    location: "Iceland",
    date: "1/25/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Iceland"],
    order: 100,
    latitude: 64.9399395,
    longitude: -23.3085596,
  },
  {
    category: "Landscape",
    name: "Laguna Amarga Sunrise",
    code: "Amarga-Sunrise",
    imageUrl: "Laguna-Amarga-Sunrise",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Torres del Paine"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Aerial",
    name: "Crystal Lake",
    code: "Mammoth-Lakes",
    imageUrl: "Mammoth-Lakes",
    location: "Mammoth Lakes, California",
    date: "1/26/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["California"],
    order: 100,
    latitude: 37.5955759,
    longitude: -119.0182911,
  },
  {
    category: "Landscape",
    name: "Maroon Bells",
    code: "Maroon-Bells-Colorado",
    imageUrl: "Maroon-Bells-Colorado",
    location: "Aspen, Colorado",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
    latitude: 39.0981336,
    longitude: -106.9447112,
  },
  {
    category: "Landscape",
    name: "Maroon Lake",
    code: "Maroon-Lake-Colorado",
    imageUrl: "Maroon-Lake-Colorado",
    location: "Aspen, Colorado",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
    latitude: 39.0981336,
    longitude: -106.9447112,
  },
  {
    category: "Landscape",
    name: "Mirador Las Torres",
    code: "Mirador-Las-Torres",
    imageUrl: "Mirador-Las-Torres",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9429016,
    longitude: -72.9486378,
  },
  {
    category: "Underwater",
    name: "Moorea",
    code: "Moorea",
    imageUrl: "Moorea",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Moorea", "French Polynesia"],
    order: 100,
    latitude: -17.4719273,
    longitude: -149.9614792,
  },
  {
    category: "Underwater",
    name: "Patagonia Kelp Forest",
    code: "Patagonia-Kelp-Forest",
    imageUrl: "Patagonia-Kelp-Forest",
    location: "Ushuaia, Patagonia, Argentina",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -54.8671241,
    longitude: -68.2524701,
  },
  {
    category: "Landscape",
    name: "Lago Pehoe 1",
    code: "Pehoe-Paine",
    imageUrl: "Pehoe-Paine",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -51.1015445,
    longitude: -72.9800617,
  },
  {
    category: "Astrophotography",
    name: "Lago Pehoe 2",
    code: "Pehoe-Astro",
    imageUrl: "Pehoe-Astro",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -51.1015445,
    longitude: -72.9800617,
  },
  {
    category: "Aerial",
    name: "Puerto Galera",
    code: "Puerto-Galera-Philippines",
    imageUrl: "Puerto_Galera",
    location: "Puerto Galera, Philippines",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Philippines"],
    order: 100,
    latitude: 13.521951,
    longitude: 120.9624714,
  },
  {
    category: "Aerial",
    name: "Puerto Galera",
    code: "Puerto-Galera-Philippines-2",
    imageUrl: "Optimized/puerto-galera",
    location: "Puerto Galera, Philippines",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Philippines"],
    order: 100,
    latitude: 13.5253572,
    longitude: 120.9811375,
  },
  {
    category: "Underwater",
    name: "Canyons",
    code: "Canyons-Puerto-Galera",
    imageUrl: "Optimized/Canyons",
    location: "Puerto Galera, Philippines",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Philippines"],
    order: 100,
    latitude: 13.5327342,
    longitude: 120.959303,
  },
  {
    category: "Underwater",
    name: "Cocos Island Jacks",
    code: "cocos-island-jacks",
    imageUrl: "Optimized/cocos-island-jacks-2",
    location: "Cocos Island, Costa Rica",
    date: "7/15/2019",
    camera: "Canon EOS 5D Mk III",
    tags: ["Costa Rica"],
    order: 100,
    latitude: 5.5244437,
    longitude: -87.0738735,
  },
  {
    category: "Underwater",
    name: "Engulfed",
    code: "cocos-island-engulfed",
    imageUrl: "Optimized/cocos-island-jacks",
    location: "Cocos Island, Costa Rica",
    date: "7/16/2019",
    camera: "Canon EOS 5D Mk III",
    tags: ["Costa Rica"],
    order: 100,
    latitude: 5.517433,
    longitude: -87.036359,
  },
  {
    category: "Underwater",
    name: "DeepSee Submersible",
    code: "deep-see",
    imageUrl: "Optimized/DeepSee",
    location: "Cocos Island, Costa Rica",
    date: "7/17/2019",
    camera: "Canon EOS 5D Mk III",
    tags: ["Costa Rica"],
    order: 100,
    latitude: 5.560514,
    longitude: -87.045008,
  },
  {
    category: "Pumas",
    name: "Puma Approaches",
    code: "Puma-Approaching",
    imageUrl: "Puma-Approaching",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Asleep in the Bush",
    code: "Puma-Asleep-In-Bushes",
    imageUrl: "Puma-Asleep-In-Bushes",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Climbing",
    code: "Puma-Climbing",
    imageUrl: "Puma-Climbing",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Crossing the Road",
    code: "Puma-in-Road",
    imageUrl: "Puma-in-Road",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Cubs Gazing",
    code: "Puma-Cubs-Gazing",
    imageUrl: "Puma-Cubs-Gazing",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Drinking",
    code: "Puma-Drinking",
    imageUrl: "Puma-Drinking",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Family on the Beach",
    code: "Puma-Family-On-Beach-1",
    imageUrl: "Puma-Family-On-Beach-1",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Family on the Beach",
    code: "Puma-Family-On-Beach-2",
    imageUrl: "Puma-Family-On-Beach-2",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Family on the Beach",
    code: "Puma-Family-On-Beach-3",
    imageUrl: "Puma-Family-On-Beach-3",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Family Resting",
    code: "Puma-Family-Resting",
    imageUrl: "Puma-Family-Resting",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Mother \u0026 Cub",
    code: "Puma-Mother-Cub",
    imageUrl: "Puma-Mother-Cub",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Peeks",
    code: "Puma-Peek",
    imageUrl: "Puma-Peek",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Scent",
    code: "Puma-Scent",
    imageUrl: "Puma-Scent",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Siblings",
    code: "Puma-Siblings",
    imageUrl: "Puma-Siblings",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Puma Stretching",
    code: "Puma-Stretch",
    imageUrl: "Puma-Stretch",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Pumas in the Bushes",
    code: "Pumas-In-Bushes",
    imageUrl: "Pumas-In-Bushes",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Pumas Las Torres",
    code: "Puma-Las-Torres",
    imageUrl: "Puma-Las-Torres.jpg",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Pumas on a Hilltop",
    code: "Pumas-Hilltop",
    imageUrl: "Pumas-Hilltop",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Pumas on the Horizon",
    code: "Pumas-on-Horizon",
    imageUrl: "Pumas-on-Horizon",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Pumas",
    name: "Pumas Wrestling",
    code: "Pumas-Playing",
    imageUrl: "Pumas-Playing",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
    latitude: -50.9754707,
    longitude: -72.7542263,
  },
  {
    category: "Underwater",
    name: "Raggedtooh Shark",
    code: "Raggie",
    imageUrl: "Raggie",
    location: "Wild Coast, South Africa",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["South Africa", "Sharks"],
    order: 100,
    latitude: -31.6321454,
    longitude: 29.5670639,
  },
  {
    category: "Underwater",
    name: "Great White Shark",
    code: "great-white-shark",
    imageUrl: "Optimized/great-white-",
    location: "Cape Town, South Africa",
    date: "1/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["South Africa", "Sharks"],
    order: 100,
    latitude: -34.201985,
    longitude: 18.566947,
  },
  {
    category: "Underwater",
    name: "Red Sea Reef",
    code: "Red-Sea-Reef",
    imageUrl: "Red-Sea-Reef",
    location: "Red Sea, Egypt",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 25.198925,
    longitude: 35.780192,
  },
  {
    category: "Landscape",
    name: "Routeburn Falls",
    code: "Routeburn-New-Zealand",
    imageUrl: "Routeburn-New-Zealand",
    location: "New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -44.7260077,
    longitude: 168.1992213,
  },
  {
    category: "Underwater",
    name: "Silfra Fissure",
    code: "Silfra",
    imageUrl: "silfra",
    location: "Iceland",
    date: "7/20/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 64.2544555,
    longitude: -21.1183057,
  },
  {
    category: "Underwater",
    name: "Silky Cluster",
    code: "Silky-Sharks",
    imageUrl: "Silky-Sharks",
    location: "Jardines de la Reina, Cuba",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 20.8416771,
    longitude: -78.9375894,
  },
  {
    category: "Underwater",
    name: "Silky Portrait",
    code: "Silky-Portrait",
    imageUrl: "Silky-Portrait",
    location: "Jardines de la Reina, Cuba",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 20.8416771,
    longitude: -78.9375894,
  },
  {
    category: "Landscape",
    name: "Te Waikoropupu Springs",
    code: "Te-Waikoropupu-Springs-New-Zealand",
    imageUrl: "Te-Waikoropupu-Springs-New-Zealand",
    location: "New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -40.8477817,
    longitude: 172.7689854,
  },
  {
    category: "Landscape",
    name: "Torres del Paine",
    code: "Torred-del-Paine",
    imageUrl: "TorresDelPaine",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -51.1236918,
    longitude: -73.1409474,
  },
  {
    category: "Landscape",
    name: "Vestrahorn",
    code: "Vestrahorn-Iceland",
    imageUrl: "Vestrahorn-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 64.2446368,
    longitude: -14.9667399,
  },
  {
    category: "Landscape",
    name: "Road to Fitz Roy",
    code: "Fitz-Roy",
    imageUrl: "Fitz-Roy",
    location: "El Chalten, Argentina",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -49.3429484,
    longitude: -72.8656959,
  },
  {
    category: "Landscape",
    name: "Fall Colors in Patagonia",
    code: "Fall-Colors-Patagonia",
    imageUrl: "Fall-Colors-Patagonia",
    location: "Tierra del Fuego, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -52.7371748,
    longitude: -69.3870305,
  },
  {
    category: "Underwater",
    name: "Fakarava",
    code: "Fakarava-Split",
    imageUrl: "Optimized/Fakarava-Split",
    location: "Fakarava, French Polynesia",
    date: "11/1/2019",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -16.2719069,
    longitude: -145.5559561,
  },
  {
    category: "Underwater",
    name: "Fakarava Reef",
    code: "Fakarava-Reef",
    imageUrl: "Optimized/Fakarava-Reef",
    location: "Fakarava, French Polynesia",
    date: "11/1/2019",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -16.5138577,
    longitude: -145.4643735,
  },
  {
    category: "Underwater",
    name: "Jack Tornado",
    code: "Eye-of-the-Tornado",
    imageUrl: "Optimized/Eye-of-the-Tornado",
    location: "Baja, Mexico",
    date: "11/1/2019",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 23.4352486,
    longitude: -109.4265872,
  },
  {
    category: "Underwater",
    name: "Whale Shark",
    code: "Red-Sea-Whale-Shark",
    imageUrl: "Red-Sea-Whale-Shark",
    location: "Red Sea, Egypt",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: 25.0151945,
    longitude: 35.5723548,
  },
  {
    category: "Landscape",
    name: "Wharariki Beach",
    code: "Wharariki-Beach-New-Zealand",
    imageUrl: "Wharariki-Beach-New-Zealand",
    location: "New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
    latitude: -40.5016557,
    longitude: 172.6768832,
  },
  {
    category: "Aerial",
    name: "Wolf Island",
    code: "Wolf-Island-Galapagos",
    imageUrl: "Wolf",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
    latitude: 1.384518,
    longitude: -91.8273462,
  },
  {
    category: "Aerial",
    name: "Darwin\u0027s Arch",
    code: "Darwins-Arch-Galapagos-2",
    imageUrl: "Darwins_Arch_Aerial",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Galápagos"],
    order: 200,
    latitude: 1.678061,
    longitude: -92.0122074,
  },
  {
    category: "Aerial",
    name: "Ghost Ranch",
    code: "Ghost-Ranch-New-Mexico",
    imageUrl: "Ghost-Ranch-New-Mexico",
    location: "Ghost Ranch, New Mexico",
    date: "1/29/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["New Mexico"],
    order: 200,
    latitude: 36.3271663,
    longitude: -106.478243,
  },
  {
    category: "Landscape",
    name: "Blagaj Dervish House",
    code: "Bosnia-Herzegovina-1",
    imageUrl: "Optimized/Bosnia-1",
    location: "Bosnia & Herzegovina",
    date: "7/1/2016",
    camera: "Canon EOS 5D Mk III",
    tags: ["Bosnia & Herzegovina"],
    order: 200,
    latitude: 43.257071,
    longitude: 17.9026705,
  },
  {
    category: "Landscape",
    name: "Bosnia & Herzegovina Countryside",
    code: "Bosnia-Herzegovina-2",
    imageUrl: "Optimized/Bosnia-2",
    location: "Bosnia & Herzegovina",
    date: "7/1/2016",
    camera: "Canon EOS 5D Mk III",
    tags: ["Bosnia & Herzegovina"],
    order: 200,
    latitude: 42.943798,
    longitude: 18.003825,
  },
  {
    category: "Landscape",
    name: "Mostar",
    code: "Mostar",
    imageUrl: "Optimized/Mostar",
    location: "Mostar, Bosnia & Herzegovina",
    date: "7/1/2016",
    camera: "Canon EOS 5D Mk III",
    tags: ["Bosnia & Herzegovina"],
    order: 200,
    latitude: 43.3397489,
    longitude: 17.81038,
  },
  {
    category: "Aerial",
    name: "Amalfi Coast",
    code: "Amalfi-Coast",
    imageUrl: "Optimized/Amalfi",
    location: "Amalfi, Italy",
    date: "7/1/2016",
    camera: "DJI Phantom 3 Pro",
    tags: ["Italy"],
    order: 200,
    latitude: 40.6331541,
    longitude: 14.6038106,
  },
  {
    category: "Aerial",
    name: "Makarska Riviera",
    code: "Makarska-Riviera",
    imageUrl: "Optimized/Makarska-Riviera",
    location: "Makarska Riviera, Croatia",
    date: "7/1/2016",
    camera: "DJI Phantom 3 Pro",
    tags: ["Croatia"],
    order: 200,
    latitude: 43.217904,
    longitude: 17.1061145,
  },
  {
    category: "Aerial",
    name: "Plitvice Lakes",
    code: "Plitvice-1",
    imageUrl: "Optimized/Plitvice-1",
    location: "Plitvice National Park, Croatia",
    date: "7/1/2016",
    camera: "DJI Phantom 3 Pro",
    tags: ["Croatia"],
    order: 200,
    latitude: 44.873876,
    longitude: 15.603307,
  },
  {
    category: "Aerial",
    name: "Plitvice Lakes",
    code: "Plitvice-2",
    imageUrl: "Optimized/Plitvice-2",
    location: "Plitvice National Park, Croatia",
    date: "7/1/2016",
    camera: "DJI Phantom 3 Pro",
    tags: ["Croatia"],
    order: 200,
    latitude: 44.873876,
    longitude: 15.603307,
  },
  {
    category: "Landscape",
    name: "Olympic Village",
    code: "vanvouver-bc",
    imageUrl: "Optimized/vanvouver-bc",
    location: "Vancouver, BC",
    date: "1/1/2016",
    camera: "Canon 5D Mk III",
    tags: ["Canada", "British Columbia"],
    order: 200,
    latitude: 49.2713392,
    longitude: -123.1261487,
  },
  {
    category: "Underwater",
    name: "Hell's Bells Cenote",
    code: "hells-bells-cenote",
    imageUrl: "Optimized/hells-bells",
    location: "Hell's Bells Cenote, Mexico",
    date: "11/10/2019",
    camera: "Canon 5D Mk III",
    tags: ["Mexico"],
    order: 200,
    latitude: 20.8538528,
    longitude: -87.1254546,
  },
];

export function getImageUrl(code, w, h) {
  const width = w > 0 ? ",w_" + w : "";
  const height = h > 0 ? ",h_" + h : "";
  return `https://res.cloudinary.com/dtgitfbtp/image/upload/q_auto,f_auto,g_custom,c_fill${width}${height}/${code}`;
  // return `https://res.cloudinary.com/dtgitfbtp/image/upload/q_auto,f_auto,g_custom,c_fill${width}${height},dpr_2.0/${code}`;
}

export function getAll() {
  return images.sort((a, b) => (a.longitude > b.longitude ? 1 : -1));
}

export function getImages(category) {
  return images.filter((image) => image.category.toLowerCase() === category.toLowerCase());
}

export function getImage(code) {
  return images.find(function (image) {
    return image.code.toLowerCase() === code.toLowerCase();
  });
}

export function getCategory(category) {
  switch (category) {
    case "underwater":
      return "Underwater";
    case "landscape":
      return "Landscape";
    case "pumas":
      return "Pumas";
    case "aerial":
      return "Aerial";
    case "astrophotography":
      return "Astrophotography";
    default:
      return null;
  }
}

export default {
  getAll,
  getImages,
  getImage,
  getCategory,
  getImageUrl,
};
