const images = [
  {
    category: "Astrophotography",
    name: "Maroon Bells",
    code: "Maroon-Bells-Night",
    imageUrl: "Maroon-Bells-Night",
    location: "Aspen, Colorado",
    date: "2/1/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 0,
  },
  {
    category: "Underwater",
    name: "Sunset Silkies",
    code: "Sunset-Silkies",
    imageUrl: "Sunset-Silkies",
    location: "Jardines de la Reina, Cuba",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Sharks", "Cuba"],
    order: 0,
  },
  {
    category: "Underwater",
    name: "American Crocodile",
    code: "American-Crocodile",
    imageUrl: "American-Crocodile",
    location: "Jardines de la Reina, Cuba",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 10,
  },
  {
    category: "Underwater",
    name: "Golden Rays",
    code: "Golden-Rays",
    imageUrl: "Golden-Rays",
    location: "Galápagos, Ecuador",
    date: "9/25/2016",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 20,
  },
  {
    category: "Underwater",
    name: "Humpback Portrait",
    code: "Humpback-Portrait",
    imageUrl: "Humpback-Portrait",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 30,
  },
  {
    category: "Underwater",
    name: "Humpbacks Surfacing",
    code: "Humpbacks-Surfacing",
    imageUrl: "humpbacks-surfacing",
    location: "Moorea, French Polynesia",
    date: "5/17/2016",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 45,
  },
  {
    category: "Underwater",
    name: "Kelp Forest",
    code: "Kelp-Forest",
    imageUrl: "kelp-forest",
    location: "Santa Barbara Islamd, California",
    date: "7/26/2015",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 50,
  },
  {
    category: "Underwater",
    name: "American Crocodile Swimming",
    code: "American-Crocodile-Swimming",
    imageUrl: "American-Crocodile-Swimming",
    location: "Jardines de la Reina, Cuba",
    date: "7/6/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Crocodiles", "Cuba"],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Aspen",
    code: "Aspen-Colorado",
    imageUrl: "Aspen-Colorado",
    location: "Aspen, Colorado, USA",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Astrophotography",
    name: "Aurora Australis",
    code: "Aurora-Wanaka-New-Zealand",
    imageUrl: "Aurora-Wanaka-New-Zealand",
    location: "Wanaka, New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Bartolome Island",
    code: "Bartolome-Galapagos",
    imageUrl: "Bartolome-Galapagos",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Astrophotography",
    name: "Boulder",
    code: "Boulder-Colorado",
    imageUrl: "Boulder-Colorado",
    location: "Boulder, Colorado, USA",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Carwash Cenote",
    code: "Carwash-Cenote",
    imageUrl: "Carwash-Cenote",
    location: "Mexico",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Colorado",
    code: "Colorado-Snow-Aerial",
    imageUrl: "Colorado-Snow-Aerial",
    location: "Aspen, Colorado",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Cuba",
    code: "Cuba-Reef",
    imageUrl: "Cuba-Reef",
    location: "Jardines de la Reina, Cuba",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Cuernos Splitshot",
    code: "Cuernos-Splitshot",
    imageUrl: "Cuernos-Splishot",
    location: "Torres del Paine, Patagonia, Chile",
    date: "7/10/2016",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Darwin\u0027s Arch",
    code: "Darwins-Arch-Galapagos",
    imageUrl: "Darwins-Arch-Galapagos",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Galápagos"],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Davidsgja",
    code: "Davidsgja",
    imageUrl: "Davidsgja",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Dreamgate Cenote",
    code: "Dreamgate",
    imageUrl: "Dreamgate",
    location: "Mexico",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Dynjandi, Iceland",
    code: "Dynjandi-Iceland",
    imageUrl: "Dynjandi-Iceland",
    location: "Iceland",
    date: "1/28/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Gjáin",
    code: "Gjáin-Iceland",
    imageUrl: "Gjáin-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Glacier in Iceland",
    code: "Glacier-Iceland",
    imageUrl: "Glacier-Iceland",
    location: "Iceland",
    date: "1/27/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Golden Aspens",
    code: "Golden-Aspens-Vail-Colorado",
    imageUrl: "Golden-Aspens-Vail-Colorado",
    location: "Vail, Colorado, USA",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Astrophotography",
    name: "Great Sand Dunes",
    code: "Great-Sand-Dunes-Colorado",
    imageUrl: "Great-Sand-Dunes-Colorado",
    location: "Colorado, USA",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Green Sea Turtle",
    code: "Green-Sea-Turtle",
    imageUrl: "Green-Sea-Turtle",
    location: "Red Sea, Egypt",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Haiti Aerial",
    code: "Haiti-Aerial",
    imageUrl: "Haiti-Aerial",
    location: "Haiti",
    date: "1/31/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Humback Inversion",
    code: "Humback-Inversion",
    imageUrl: "Humpback-Inversion",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Humback Whales",
    code: "Humback-Whales",
    imageUrl: "Humpback-Whales",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Hverir",
    code: "Hverir-Iceland",
    imageUrl: "Hverir-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Icelandic Farm",
    code: "Icelandic-Farm",
    imageUrl: "Icelandic-Farm",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Kirkjufell",
    code: "Kirkjufell-Iceland",
    imageUrl: "Kirkjufell-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Iceland"],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Kirkjufell, Iceland",
    code: "Kirkjufell-Iceland",
    imageUrl: "Kirkjufell-Aerial-Iceland",
    location: "Iceland",
    date: "1/25/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Iceland"],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Laguna Amarga Sunrise",
    code: "Amarga-Sunrise",
    imageUrl: "Laguna-Amarga-Sunrise",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Mammoth Lakes, California",
    code: "Mammoth-Lakes",
    imageUrl: "Mammoth-Lakes",
    location: "Mammoth Lakes, California",
    date: "1/26/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["California"],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Maroon Bells",
    code: "Maroon-Bells-Colorado",
    imageUrl: "Maroon-Bells-Colorado",
    location: "Aspen, Colorado, USA",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Maroon Lake",
    code: "Maroon-Lake-Colorado",
    imageUrl: "Maroon-Lake-Colorado",
    location: "Aspen, Colorado, USA",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Colorado"],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Mirador Las Torres",
    code: "Mirador-Las-Torres",
    imageUrl: "Mirador-Las-Torres",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: ["Patagonia", "Chile"],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Moorea",
    code: "Moorea",
    imageUrl: "Moorea",
    location: "Moorea, French Polynesia",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: ["Moorea", "French Polynesia"],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Patagonia Kelp Forest",
    code: "Patagonia-Kelp-Forest",
    imageUrl: "Patagonia-Kelp-Forest",
    location: "Ushuaia, Patagonia, Argentina",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Pehoe",
    code: "Pehoe-Paine",
    imageUrl: "Pehoe-Paine",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Astrophotography",
    name: "Pehoe",
    code: "Pehoe-Astro",
    imageUrl: "Pehoe-Astro",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Puerto Galera, Philippines",
    code: "Puerto-Galera-Philippines",
    imageUrl: "Puerto_Galera",
    location: "Puerto Galera, Philippines",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Approaches",
    code: "Puma-Approaching",
    imageUrl: "Puma-Approaching",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Asleep in the Bush",
    code: "Puma-Asleep-In-Bushes",
    imageUrl: "Puma-Asleep-In-Bushes",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Climbing",
    code: "Puma-Climbing",
    imageUrl: "Puma-Climbing",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Crossing the Road",
    code: "Puma-in-Road",
    imageUrl: "Puma-in-Road",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Cubs Gazing",
    code: "Puma-Cubs-Gazing",
    imageUrl: "Puma-Cubs-Gazing",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Drinking",
    code: "Puma-Drinking",
    imageUrl: "Puma-Drinking",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Family on the Beach",
    code: "Puma-Family-On-Beach-1",
    imageUrl: "Puma-Family-On-Beach-1",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Family on the Beach",
    code: "Puma-Family-On-Beach-2",
    imageUrl: "Puma-Family-On-Beach-2",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Family on the Beach",
    code: "Puma-Family-On-Beach-3",
    imageUrl: "Puma-Family-On-Beach-3",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Family Resting",
    code: "Puma-Family-Resting",
    imageUrl: "Puma-Family-Resting",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Mother \u0026 Cub",
    code: "Puma-Mother-Cub",
    imageUrl: "Puma-Mother-Cub",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Peeks",
    code: "Puma-Peek",
    imageUrl: "Puma-Peek",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Scent",
    code: "Puma-Scent",
    imageUrl: "Puma-Scent",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Siblings",
    code: "Puma-Siblings",
    imageUrl: "Puma-Siblings",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Puma Stretching",
    code: "Puma-Stretch",
    imageUrl: "Puma-Stretch",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Pumas in the Bushes",
    code: "Pumas-In-Bushes",
    imageUrl: "Pumas-In-Bushes",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Pumas Las Torres",
    code: "Puma-Las-Torres",
    imageUrl: "Puma-Las-Torres.jpg",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Pumas on a Hilltop",
    code: "Pumas-Hilltop",
    imageUrl: "Pumas-Hilltop",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Pumas on the Horizon",
    code: "Pumas-on-Horizon",
    imageUrl: "Pumas-on-Horizon",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Pumas",
    name: "Pumas Wrestling",
    code: "Pumas-Playing",
    imageUrl: "Pumas-Playing",
    location: "Patagonia, Chile",
    date: "3/1/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Raggie",
    code: "Raggie",
    imageUrl: "Raggie",
    location: "South Africa",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Red Sea Reef",
    code: "Red-Sea-Reef",
    imageUrl: "Red-Sea-Reef",
    location: "Red Sea, Egypt",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Routeburn Falls",
    code: "Routeburn-New-Zealand",
    imageUrl: "Routeburn-New-Zealand",
    location: "New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Silfra Fissure",
    code: "Silfra",
    imageUrl: "silfra",
    location: "Iceland",
    date: "7/20/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Silky Cluster",
    code: "Silky-Sharks",
    imageUrl: "Silky-Sharks",
    location: "Jardines de la Reina, Cuba",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Silky Portrait",
    code: "Silky-Portrait",
    imageUrl: "Silky-Portrait",
    location: "Jardines de la Reina, Cuba",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Te Waikoropupu Springs",
    code: "Te-Waikoropupu-Springs-New-Zealand",
    imageUrl: "Te-Waikoropupu-Springs-New-Zealand",
    location: "New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Torres del Paine",
    code: "Torred-del-Paine",
    imageUrl: "TorresDelPaine",
    location: "Patagonia, Chile",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Vestrahorn",
    code: "Vestrahorn-Iceland",
    imageUrl: "Vestrahorn-Iceland",
    location: "Iceland",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Underwater",
    name: "Whale Shark",
    code: "Red-Sea-Whale-Shark",
    imageUrl: "Red-Sea-Whale-Shark",
    location: "Red Sea, Egypt",
    date: "1/1/2018",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Landscape",
    name: "Wharariki Beach",
    code: "Wharariki-Beach-New-Zealand",
    imageUrl: "Wharariki-Beach-New-Zealand",
    location: "New Zealand",
    date: "1/24/2017",
    camera: "Canon EOS 5D Mk III",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Wolf Island, Galapagos",
    code: "Wolf-Island-Galapagos",
    imageUrl: "Wolf",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: [],
    order: 100,
  },
  {
    category: "Aerial",
    name: "Darwin\u0027s Arch, Galapagos",
    code: "Darwins-Arch-Galapagos-2",
    imageUrl: "Darwins_Arch_Aerial",
    location: "Galápagos, Ecuador",
    date: "1/24/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["Galápagos"],
    order: 200,
  },
  {
    category: "Aerial",
    name: "Ghost Ranch, New Mexico",
    code: "Ghost-Ranch-New-Mexico",
    imageUrl: "Ghost-Ranch-New-Mexico",
    location: "Ghost Ranch, New Mexico",
    date: "1/29/2017",
    camera: "DJI Phantom 3 Pro",
    tags: ["New Mexico"],
    order: 200,
  },
];

export function getImageUrl(code, w, h) {
  const width = w > 0 ? ",w_" + w : "";
  const height = h > 0 ? ",h_" + h : "";
  return `https://res.cloudinary.com/dtgitfbtp/image/upload/q_auto,f_auto,g_custom,c_fill${width}${height},dpr_2.0/${code}`;
}

export function getImages(category) {
  return images.filter((image) => image.category.toLowerCase() === category.toLowerCase());
}

export function getImage(code) {
  return images.find(function (image) {
    return image.code.toLowerCase() === code.toLowerCase();
  });
}

export function getCategory(category) {
  switch (category) {
    case "underwater":
      return "Underwater";
    case "landscape":
      return "Landscape";
    case "pumas":
      return "Pumas";
    case "aerial":
      return "Aerial";
    case "astrophotography":
      return "Astrophotography";
    default:
      return null;
  }
}

export default {
  getImages,
  getImage,
  getCategory,
  getImageUrl,
};
